# Generated by Django 2.1.15 on 2022-07-08 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Metrics', models.CharField(max_length=4)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomatedUnitTestingEffectiveness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Month_of_Metrics', models.CharField(max_length=20)),
                ('Unit_Testing_Coverage', models.FloatField()),
                ('Percentage_Of_Unit_Cases_Passed', models.FloatField()),
                ('AUTE', models.FloatField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Client_Details', models.CharField(max_length=64)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefectSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DefectSource', models.CharField(max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='DefectSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Month_of_Metrics', models.CharField(max_length=20)),
                ('DefectId', models.CharField(max_length=32)),
                ('Severity', models.CharField(max_length=32)),
                ('DefectSource', models.CharField(max_length=32)),
                ('RC', models.CharField(max_length=32)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EffortVariance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Month_of_Metrics', models.CharField(max_length=20)),
                ('Planned_Effort', models.FloatField()),
                ('Actual_Effort', models.FloatField()),
                ('EV', models.FloatField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterProject',
            fields=[
                ('Client', models.CharField(max_length=24)),
                ('MasterProject', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('MasterProject_Details', models.CharField(max_length=64)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('Metrics', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Metrics_Details', models.CharField(max_length=64)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricsBenchMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metrics', models.CharField(max_length=24)),
                ('Month', models.CharField(max_length=24)),
                ('BenchMark', models.FloatField()),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricsMonth',
            fields=[
                ('Month', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=1)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricsMonthStatus',
            fields=[
                ('Status', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=16)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnTimeDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Month_of_Metrics', models.CharField(max_length=20)),
                ('Total_Delivery', models.IntegerField(default=0)),
                ('Total_Delivery_OnTime', models.IntegerField(default=0)),
                ('OTD', models.FloatField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Client', models.CharField(max_length=24)),
                ('Project_MasterProject', models.CharField(max_length=24)),
                ('Project', models.CharField(max_length=24)),
                ('Project_Key', models.CharField(max_length=72)),
                ('Project_Details', models.CharField(max_length=72)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('Project_Key', models.CharField(max_length=72, primary_key=True, serialize=False)),
                ('Project_PM_EmpId', models.IntegerField(default=0)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QARemovalEfficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Month_of_Metrics', models.CharField(max_length=20)),
                ('QA_Defects', models.IntegerField(default=0)),
                ('After_QA_Defects', models.IntegerField(default=0)),
                ('DRE', models.FloatField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RC', models.CharField(max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role', models.CharField(default='B', max_length=1, primary_key=True, serialize=False)),
                ('Role_Details', models.CharField(max_length=10)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subordinates',
            fields=[
                ('PM_EmpId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Sub_EmpId', models.IntegerField(default=0)),
                ('Created_by', models.CharField(max_length=24)),
                ('Created_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TmpPswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pswd', models.CharField(default='Celsior', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UsrLgn',
            fields=[
                ('UsrLgn_EmpId', models.IntegerField(default=0)),
                ('UsrLgnName', models.CharField(default='Celsior', max_length=20, primary_key=True, serialize=False)),
                ('UsrLgnPswd', models.CharField(default='Celsior', max_length=128)),
                ('UsrLgn_Lst_Pswd', models.CharField(default='Celsior', max_length=128)),
                ('UsrLgn_Email', models.EmailField(default='Celsior.com', max_length=32)),
                ('UsrLgn_Role', models.CharField(default='B', max_length=1)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='WeightedCodeReviewEffectiveness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Month_of_Metrics', models.CharField(max_length=20)),
                ('Static_CR', models.CharField(max_length=1)),
                ('Peer_CR', models.CharField(max_length=1)),
                ('Arch_CR', models.CharField(max_length=1)),
                ('No_Of_Object', models.IntegerField(default=0)),
                ('No_Of_Object_StaticReview', models.IntegerField(default=0)),
                ('No_Of_Object_PeerReviewed', models.IntegerField(default=0)),
                ('No_Of_Object_ArchReviewed', models.IntegerField(default=0)),
                ('No_Of_ReviewComments', models.IntegerField(default=0)),
                ('No_Of_ReviewComments_Incorporated', models.IntegerField(default=0)),
                ('WCRE', models.FloatField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightedDefectDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Key', models.CharField(max_length=72)),
                ('Month_of_Metrics', models.CharField(max_length=20)),
                ('Dev_Hours', models.FloatField()),
                ('No_Of_Critical_Defects', models.IntegerField(default=0)),
                ('No_Of_High_Defects', models.IntegerField(default=0)),
                ('No_Of_Medium_Defects', models.IntegerField(default=0)),
                ('No_Of_Low_Defects', models.IntegerField(default=0)),
                ('WDD', models.FloatField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Created_by', models.CharField(default='SW-METRICS', max_length=24, null=True)),
                ('Created_Date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weighteddefectdensity',
            unique_together={('Project_Key', 'Month_of_Metrics')},
        ),
        migrations.AlterUniqueTogether(
            name='weightedcoderevieweffectiveness',
            unique_together={('Project_Key', 'Month_of_Metrics')},
        ),
        migrations.AlterUniqueTogether(
            name='qaremovalefficiency',
            unique_together={('Project_Key', 'Month_of_Metrics')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('Project_Client', 'Project_MasterProject', 'Project', 'Project_Key')},
        ),
        migrations.AlterUniqueTogether(
            name='ontimedelivery',
            unique_together={('Project_Key', 'Month_of_Metrics')},
        ),
        migrations.AlterUniqueTogether(
            name='metricsbenchmark',
            unique_together={('Metrics', 'Month')},
        ),
        migrations.AlterUniqueTogether(
            name='effortvariance',
            unique_together={('Project_Key', 'Month_of_Metrics')},
        ),
        migrations.AlterUniqueTogether(
            name='defectsummary',
            unique_together={('Project_Key', 'Month_of_Metrics', 'DefectId')},
        ),
        migrations.AlterUniqueTogether(
            name='automatedunittestingeffectiveness',
            unique_together={('Project_Key', 'Month_of_Metrics')},
        ),
        migrations.AlterUniqueTogether(
            name='appmetrics',
            unique_together={('Project_Key', 'Metrics')},
        ),
    ]
